# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 3, 13, 0, 34, 385954, tzinfo=utc)),
        ),
    ]
